Repository Emmanuel-Melon/inspirers, pull requests merged in 2022-10, with the labels that each got.

#105 docker-deployment
  .dockerignore
  .vscode/settings.json
  docker-compose.yml
  docker/Dockerfile-api
  docker/Dockerfile-docs
  docker/Dockerfile-web
Labels: enhancement, backend

#118 Goal Builder
  apps/api/src/journeys/controller.ts
  apps/api/src/journeys/operations/create.ts
  apps/api/src/journeys/operations/getById.ts
  apps/api/src/journeys/operations/list.ts
  apps/api/src/journeys/operations/update.ts
  apps/api/src/journeys/router.ts
  apps/web/Journeys/EditJourney.tsx
  apps/web/Journeys/ListJourneys.tsx
  apps/web/Journeys/Onboarding/BluePrintSelector.tsx
  apps/web/Journeys/Onboarding/JourneyGoals.tsx
  apps/web/Journeys/Onboarding/JourneyInfo.tsx
  apps/web/Journeys/Onboarding/JourneyOnboardingSteps.tsx
  apps/web/Journeys/Onboarding/JourneyType.tsx
  apps/web/Journeys/components/JourneyCard.tsx
  apps/web/Journeys/components/JourneyOverviewCard.tsx
  apps/web/Journeys/components/editor.tsx
  apps/web/Journeys/components/personal.tsx
  apps/web/pages/journeys/[id].tsx
  apps/web/pages/journeys/goals.tsx
  apps/web/pages/journeys/goals/[goal].tsx
  apps/web/pages/journeys/index.tsx
  apps/web/pages/journeys/new.tsx
  apps/web/providers/JourneyOnboardingProvider.tsx
  apps/web/providers/JourneyProvider.tsx
Labels: enhancement, frontend, backend

#122 Add logo, resize images, implement dark mode globally
  apps/api/package.json
  apps/api/src/config.ts
  apps/api/src/journeys/operations/list.ts
  apps/docs/layout/layout.tsx
  apps/docs/pages/_app.tsx
  apps/web/User/components/UserProfileCard.tsx
  apps/web/config.ts
  apps/web/layout/Nested.tsx
  apps/web/layout/layout.tsx
  apps/web/package.json
  apps/web/pages/_app.tsx
  apps/web/pages/_document.tsx
  apps/web/pages/landing.tsx
  apps/web/pages/user/[username].tsx
  apps/web/styles/global.css
  apps/web/theme.ts
  package.json
  packages/ui/Button.tsx
  yarn.lock
Labels: enhancement, frontend, WIP

#121 adding npm font
  apps/api/package.json
  apps/api/src/config.ts
  apps/web/User/components/UserProfileCard.tsx
  apps/web/config.ts
  apps/web/package.json
  apps/web/pages/_app.tsx
  apps/web/pages/landing.tsx
  apps/web/pages/user/[username].tsx
  apps/web/styles/global.css
  apps/web/theme.ts
  packages/ui/Button.tsx
  yarn.lock
Labels: frontend, ready-for-review

#120 Invitation Links
  apps/api/package.json
  apps/api/src/auth/controller.ts
  apps/api/src/config.ts
  apps/api/src/enqueue.ts
  apps/api/src/journeys/operations/create.ts
  apps/api/src/lib/sendgrid.ts
  apps/api/src/mail/worker.ts
  apps/api/src/start.ts
  apps/api/src/users/operations/create.ts
  apps/api/src/users/operations/update.ts
  apps/api/src/users/router.ts
  apps/api/src/users/worker.ts
  apps/web/Auth/components/LoginForm.tsx
  apps/web/Backpack/ListRecentlyAdded.tsx
  apps/web/Journeys/components/JourneyOverviewCard.tsx
  apps/web/User/InviteFriendModal.tsx
  apps/web/hooks/useSwr.tsx
  apps/web/package.json
  apps/web/pages/_app.tsx
  apps/web/pages/api/auth/[...nextauth].tsx
  apps/web/pages/auth/index.tsx
  apps/web/pages/join/[invite].tsx
  apps/web/pages/join/index.tsx
  apps/web/pages/landing.tsx
  apps/web/styles/global.css
  apps/web/theme.ts
  apps/web/utils/auth.tsx
  apps/web/utils/ui.ts
  packages/prisma/schema.prisma
  packages/types/User.ts
  packages/ui/Button.tsx
  packages/ui/IconButton.tsx
  packages/ui/Input.tsx
  packages/ui/Sidebar.tsx
  yarn.lock
Labels: enhancement, frontend, backend, WIP
